name: flutter_app1
description: A historical questionnaire app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_analytics: ^10.10.7
  http: ^0.13.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather_36pt-Regular.ttf
        - asset: assets/fonts/Merriweather_36pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather_36pt-Italic.ttf
          style: italic